CREATE TABLE sales_by_state(
	date VARCHAR(30),
	state VARCHAR(50),
	vehicle_category VARCHAR(30),
	electric_vehicles_sold INT,
	total_vehicles_sold INT
);

SELECT * FROM sales_by_state;

CREATE TABLE sales_by_makers(
	date VARCHAR(30),
	vehicle_category VARCHAR(30),
	maker VARCHAR(50),
	electric_vehicles_sold INT
);

SELECT * FROM sales_by_makers;

CREATE TABLE dim_date(
	date VARCHAR(30),
	fiscal_year INT,
	quarter VARCHAR(10)
);

SELECT * FROM dim_date;

-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------

-- ALTERING THE STATE NAME

UPDATE sales_by_state
SET STATE = 'Andaman & Nicobar Island'
WHERE STATE = 'Andaman & Nicobar';

-- CREATING A PRIMARY KEY AND FOREIGN KEY TO THE TABLES

ALTER TABLE dim_date
ADD CONSTRAINT DATE_PK
PRIMARY KEY (date);

ALTER TABLE sales_by_state
ADD CONSTRAINT DATE_FK1
FOREIGN KEY (date)
REFERENCES dim_date(date);

ALTER TABLE sales_by_makers
ADD CONSTRAINT DATE_FK2
FOREIGN KEY (date)
REFERENCES dim_date(date);

-- Preliminary Research Questions:

-- 1. List the top 3 and bottom 3 makers for the fiscal years 2023 and 2024 
--    in terms of the number of 2-wheelers sold.

WITH AGGREGATED_VALUES AS (
	SELECT 
		EXTRACT(YEAR FROM SM.date::DATE) AS YEAR, SM.MAKER, SUM(SM.ELECTRIC_VEHICLES_SOLD) AS ELECTRIC_VEHICLES_SOLD
	FROM sales_by_makers SM
	JOIN dim_date DD ON SM.DATE = DD.DATE
	WHERE SM.VEHICLE_CATEGORY = '2-Wheelers' AND DD.FISCAL_YEAR IN (2023,2024)
	GROUP BY 1,2),

TOP3 AS(
	WITH CTE AS (
		SELECT *,
		ROW_NUMBER() OVER(PARTITION BY YEAR ORDER BY ELECTRIC_VEHICLES_SOLD DESC) AS RN
		FROM AGGREGATED_VALUES )
	SELECT YEAR, MAKER, ELECTRIC_VEHICLES_SOLD
	FROM CTE 
	WHERE RN <= 3
),

BOTTOM3 AS(
	WITH CTE AS (
		SELECT *,
		ROW_NUMBER() OVER(PARTITION BY YEAR ORDER BY ELECTRIC_VEHICLES_SOLD) AS RN
		FROM AGGREGATED_VALUES )
	SELECT YEAR, MAKER, ELECTRIC_VEHICLES_SOLD
	FROM CTE 
	WHERE RN <= 3
)

SELECT YEAR,'TOP 3' AS AGG, MAKER, ELECTRIC_VEHICLES_SOLD FROM TOP3
UNION
SELECT YEAR, 'BOTTOM 3' AS AGG, MAKER, ELECTRIC_VEHICLES_SOLD FROM BOTTOM3
ORDER BY YEAR, AGG DESC, ELECTRIC_VEHICLES_SOLD DESC;

-- Penetration Rate: 
-- This metric represents the percentage of total vehicles that are electric within a specific region or category. 
-- It is calculated as:
-- 		Penetration Rate =  (Electric Vehicles Sold / Total Vehicles Sold) * 100  
-- This indicates the adoption level of electric vehicles.

-- 2. Identify the top 5 states with the highest penetration rate in 2-wheeler
--    and 4-wheeler EV sales in FY 2024.

WITH AGG_DATA AS(
	SELECT 
		STATE, VEHICLE_CATEGORY, SUM(ELECTRIC_VEHICLES_SOLD) as ELECTRIC_VEHICLES_SOLD, 
		SUM(TOTAL_VEHICLES_SOLD) as TOTAL_VEHICLES_SOLD,
		(SUM(ELECTRIC_VEHICLES_SOLD)/SUM(TOTAL_VEHICLES_SOLD))*100 AS PENETRATION_RATE
	FROM SALES_BY_STATE SS
	JOIN DIM_DATE DD ON DD.DATE = SS.DATE
	WHERE DD.FISCAL_YEAR = 2024
	GROUP BY 1,2),

TOP5 AS (
	SELECT 
		STATE, VEHICLE_CATEGORY, PENETRATION_RATE,
		ROW_NUMBER() OVER(PARTITION BY VEHICLE_CATEGORY ORDER BY PENETRATION_RATE DESC) AS RNK
	FROM AGG_DATA
)

SELECT 
	STATE, VEHICLE_CATEGORY, PENETRATION_RATE
FROM TOP5
WHERE RNK <= 5
ORDER BY 2, 3 DESC;

-- 3. List the states with negative penetration (decline) in EV sales from 2022 to 2024?

WITH AGG_DATA AS(
	SELECT 
		DD.FISCAL_YEAR AS YEAR, SS.STATE, SS.VEHICLE_CATEGORY, SS.ELECTRIC_VEHICLES_SOLD, SS.TOTAL_VEHICLES_SOLD
	FROM SALES_BY_STATE SS
	JOIN DIM_DATE DD ON SS.DATE = DD.DATE
	WHERE DD.FISCAL_YEAR IN (2022,2023,2024)
),

PENETRATION_RATE AS(
	SELECT 
		YEAR, STATE, VEHICLE_CATEGORY, SUM(ELECTRIC_VEHICLES_SOLD) AS ELECTRIC_VEHICLES_SOLD,
		SUM(TOTAL_VEHICLES_SOLD) AS TOTAL_VEHICLES_SOLD,
		ROUND((SUM(ELECTRIC_VEHICLES_SOLD::BIGINT)/SUM(TOTAL_VEHICLES_SOLD::BIGINT)*100),2) AS PENETRATION_RATE
	FROM AGG_DATA
	GROUP BY 1,2,3
),

FINAL_DATA AS (
	SELECT 
		STATE, VEHICLE_CATEGORY,  
		MAX(CASE WHEN YEAR = 2022 THEN PENETRATION_RATE END) AS PENETRATION_RATE_2022,
		MAX(CASE WHEN YEAR = 2024 THEN PENETRATION_RATE END) AS PENETRATION_RATE_2024
	FROM PENETRATION_RATE
	GROUP BY 1,2
)

SELECT 
	STATE, VEHICLE_CATEGORY, PENETRATION_RATE_2022, PENETRATION_RATE_2024
FROM FINAL_DATA
WHERE PENETRATION_RATE_2024 < PENETRATION_RATE_2022
ORDER BY 1,2;

-- 4. What are the quarterly trends based on sales volume for the top 5 EV
--    makers (4-wheelers) from 2022 to 2024?

WITH FIRST_DATA AS(
	SELECT DD.FISCAL_YEAR, DD.QUARTER, SM.VEHICLE_CATEGORY, SM.MAKER, SM.ELECTRIC_VEHICLES_SOLD
	FROM SALES_BY_MAKERS SM
	JOIN DIM_DATE DD ON SM.DATE = DD.DATE
	WHERE SM.VEHICLE_CATEGORY = '4-Wheelers' AND DD.FISCAL_YEAR IN (2022,2023,2024)),

MAKERS AS (
	SELECT MAKER, SUM(ELECTRIC_VEHICLES_SOLD) AS ELECTRIC_VEHICLES_SOLD
	FROM FIRST_DATA
	GROUP BY 1
	ORDER BY 2 DESC
	LIMIT 5
),

QUARTERLY_RESULTS AS (
	SELECT FD.MAKER, FD.FISCAL_YEAR, FD.QUARTER, SUM(FD.ELECTRIC_VEHICLES_SOLD) AS ELECTRIC_VEHICLE_SOLD
	FROM FIRST_DATA FD
	JOIN MAKERS M ON FD.MAKER = M.MAKER
	GROUP BY 1,2,3
)

SELECT 
	MAKER, FISCAL_YEAR, QUARTER, ELECTRIC_VEHICLE_SOLD
FROM QUARTERLY_RESULTS
ORDER BY 1,2,3;

-- 5. How do the EV sales and penetration rates in Delhi compare to Karnataka for 2024?

WITH AGG_DATA AS (
SELECT 
	SS.STATE, SUM(SS.ELECTRIC_VEHICLES_SOLD::BIGINT) AS ELECTRIC_VEHICLE_SOLD, 
	SUM(SS.TOTAL_VEHICLES_SOLD::BIGINT) AS TOTAL_VEHICLES_SOLD
FROM SALES_BY_STATE SS
JOIN DIM_DATE DD ON SS.DATE = DD.DATE
WHERE DD.FISCAL_YEAR = 2024 AND SS.STATE IN ('Delhi','Karnataka')
GROUP BY 1)

SELECT 
	STATE, ELECTRIC_VEHICLE_SOLD, TOTAL_VEHICLES_SOLD,
	CONCAT(ROUND((ELECTRIC_VEHICLE_SOLD/TOTAL_VEHICLES_SOLD)*100,2),'%') AS PENETRATION_RATE
FROM AGG_DATA;

-- Compound Annual Growth Rate (CAGR): CAGR measures the mean annual growth rate over a specified period longer than one year. 
-- It is calculated as:
-- 		CAGR = [(Ending Value / Beginning Value) ** 1/n] -1

-- 6. List down the compounded annual growth rate (CAGR) in 4-wheeler
--    units for the top 5 makers from 2022 to 2024.

WITH AGG_DATA AS (
	SELECT 
		DD.FISCAL_YEAR, SM.MAKER, SM.ELECTRIC_VEHICLES_SOLD AS VEHICLE_SOLD
	FROM SALES_BY_MAKERS SM
	JOIN DIM_DATE DD ON SM.DATE = DD.DATE
	WHERE SM.VEHICLE_CATEGORY = '4-Wheelers' AND DD.FISCAL_YEAR IN (2022,2023,2024) 
),

TOP5 AS (
	SELECT MAKER, SUM(VEHICLE_SOLD) AS VEHICLE_SOLD
	FROM AGG_DATA
	GROUP BY 1
	ORDER BY 2 DESC
	LIMIT 5
),

SALES_BY_YEAR AS (
	SELECT AD.FISCAL_YEAR, AD.MAKER, SUM(AD.VEHICLE_SOLD) AS VEHICLE_SOLD
	FROM TOP5 T5
	JOIN AGG_DATA AD ON T5.MAKER = AD.MAKER
	GROUP BY 1,2
	ORDER BY 1,2
),

CAGR AS (
	SELECT MAKER, 
		MAX(CASE WHEN FISCAL_YEAR = 2022 THEN VEHICLE_SOLD END) AS SALES_2022,
		MAX(CASE WHEN FISCAL_YEAR = 2024 THEN VEHICLE_SOLD END) AS SALES_2024
	FROM SALES_BY_YEAR
	GROUP BY 1
)

SELECT 
	MAKER, SALES_2022, SALES_2024,
	CASE 
		WHEN SALES_2022 > 0 THEN ROUND(((SALES_2024::NUMERIC / SALES_2022) ^ (1.0 / 2) - 1) * 100, 2)
		ELSE NULL
	END AS CAGR_VALUE
FROM CAGR;

-- 7. List down the top 10 states that had the highest compounded annual
--    growth rate (CAGR) from 2022 to 2024 in total vehicles sold.

WITH AGG_DATA AS (
	SELECT DD.DATE, DD.FISCAL_YEAR, SS.STATE, SS.VEHICLE_CATEGORY, SS.TOTAL_VEHICLES_SOLD
	FROM SALES_BY_STATE SS
	JOIN DIM_DATE DD ON SS.DATE = DD.DATE
	WHERE DD.FISCAL_YEAR IN (2022,2023,2024)
),

TOP10 AS (
	SELECT STATE, SUM(TOTAL_VEHICLES_SOLD) AS TOTAL_VEHICLE_SOLD
	FROM AGG_DATA
	GROUP BY 1
	ORDER BY 2 DESC
	LIMIT 10
),

SALES_BY_STATE AS (
	SELECT AD.FISCAL_YEAR, AD.STATE, AD.VEHICLE_CATEGORY, SUM(AD.TOTAL_VEHICLES_SOLD) AS VEHICLES_SOLD
	FROM TOP10 AS T
	JOIN AGG_DATA AS AD ON T.STATE = AD.STATE
	GROUP BY 1,2,3
	ORDER BY 1,2,3
),

CAGR AS (
	SELECT 
		STATE, VEHICLE_CATEGORY, 
		MAX( CASE WHEN FISCAL_YEAR = 2022 THEN VEHICLES_SOLD END) AS SALES_2022,
		MAX( CASE WHEN FISCAL_YEAR = 2024 THEN VEHICLES_SOLD END) AS SALES_2024
	FROM SALES_BY_STATE
	GROUP BY 1,2
	ORDER BY 1,2
)

SELECT 
	STATE, VEHICLE_CATEGORY, SALES_2022, SALES_2024,
	CASE
		WHEN SALES_2022 > 0 THEN ROUND(((SALES_2024::NUMERIC / SALES_2022) ^ (1.0 / 2) - 1) * 100, 2)
		ELSE NULL
	END AS CAGR
FROM CAGR;

-- 8. What are the peak and low season months for EV sales based on the
--    data from 2022 to 2024?

WITH AGG_DATA AS (
	SELECT 
		DD.FISCAL_YEAR AS YEAR, TO_CHAR(DD.DATE::DATE, 'MON') AS MONTH,
		SUM(SM.ELECTRIC_VEHICLES_SOLD) AS VEHICLES_SOLD
	FROM SALES_BY_MAKERS SM
	JOIN DIM_DATE DD ON SM.DATE = DD.DATE
	WHERE DD.FISCAL_YEAR IN (2022,2023,2024)
	GROUP BY 1,2
)

SELECT YEAR, MONTH, VEHICLES_SOLD
FROM AGG_DATA
WHERE VEHICLES_SOLD = (SELECT MIN(VEHICLES_SOLD) FROM AGG_DATA)

UNION ALL

SELECT YEAR, MONTH, VEHICLES_SOLD
FROM AGG_DATA
WHERE VEHICLES_SOLD = (SELECT MAX(VEHICLES_SOLD) FROM AGG_DATA)


-- 9. What is the projected number of EV sales (including 2-wheelers and 4-wheelers) for the top 10 states 
--    by penetration rate in 2030, based on the compounded annual growth rate (CAGR) from previous years?

WITH AGG_DATA AS (
	SELECT 
		DD.FISCAL_YEAR, SS.STATE, SS.VEHICLE_CATEGORY, 
		SUM(SS.ELECTRIC_VEHICLES_SOLD) AS ELECTRIC_VEHICLES_SOLD,
		SUM(SS.TOTAL_VEHICLES_SOLD) AS TOTAL_VEHICLES_SOLD,
		ROUND((SUM(SS.ELECTRIC_VEHICLES_SOLD::BIGINT)/SUM(SS.TOTAL_VEHICLES_SOLD))*100,2) AS PENETRATION_RATE
	FROM SALES_BY_STATE SS
	JOIN DIM_DATE DD ON SS.DATE = DD.DATE
	GROUP BY 1,2,3
),

CAGR AS (
	SELECT 
		STATE, VEHICLE_CATEGORY, 
		MAX(CASE WHEN FISCAL_YEAR = 2022 THEN ELECTRIC_VEHICLES_SOLD END) AS SALES_2022,
		MAX(CASE WHEN FISCAL_YEAR = 2023 THEN ELECTRIC_VEHICLES_SOLD END) AS SALES_2023,
		MAX(CASE WHEN FISCAL_YEAR = 2024 THEN ELECTRIC_VEHICLES_SOLD END) AS SALES_2024
	FROM AGG_DATA
	GROUP BY 1,2
),

PROJECTED_CAGR AS (
	SELECT 
		STATE, VEHICLE_CATEGORY, SALES_2022, SALES_2024,
		CASE
			WHEN SALES_2022 > 0 THEN ROUND(((SALES_2024::NUMERIC / SALES_2022) ^ (1.0 / 2) - 1) * 100, 2)
			ELSE NULL
		END AS CAGR,
		 -- Project EV sales for 2030: Sales_2030 = Sales_2024 * (1 + CAGR) ^ 6
        ROUND(SALES_2024 *( 1 + COALESCE(
			CASE
				WHEN SALES_2022 = 0 THEN 0
				ELSE ((SALES_2024::NUMERIC/SALES_2022)^(1.0/2)) - 1
			END
		)
		)^6 ) AS PROJECTED_SALES
	FROM CAGR
)

SELECT 
	STATE, VEHICLE_CATEGORY, SALES_2024, PROJECTED_SALES
FROM PROJECTED_CAGR
WHERE PROJECTED_SALES IS NOT NULL
ORDER BY 3 DESC
LIMIT 10;

-- 10. Estimate the revenue growth rate of 4-wheeler and 2-wheelers EVs in India for 2022 vs 2024 and
--     2023 vs 2024, assuming an average unit price of 2-Wheeler = 85k and 4-wheeler = 15L.

WITH AGG_DATA AS(
	SELECT
		DD.FISCAL_YEAR, SS.VEHICLE_CATEGORY,
		CASE 
			WHEN SS.VEHICLE_CATEGORY = '2-Wheelers' THEN SUM(SS.ELECTRIC_VEHICLES_SOLD::BIGINT * 85000)
			ELSE SUM(SS.ELECTRIC_VEHICLES_SOLD::BIGINT * 1500000)
		END AS REVENUE
	FROM SALES_BY_STATE SS
	JOIN DIM_DATE DD ON SS.DATE = DD.DATE
	WHERE DD.FISCAL_YEAR IN (2022,2023,2024)
	GROUP BY 1,2
),

REVENUE_GROWTH AS (
	SELECT 
		VEHICLE_CATEGORY,
		MAX(CASE WHEN FISCAL_YEAR = 2022 THEN REVENUE END) AS REVENUE_2022,
		MAX(CASE WHEN FISCAL_YEAR = 2023 THEN REVENUE END) AS REVENUE_2023,
		MAX(CASE WHEN FISCAL_YEAR = 2024 THEN REVENUE END) AS REVENUE_2024
	FROM AGG_DATA
	GROUP BY 1
)

SELECT 
	VEHICLE_CATEGORY,
	CONCAT('$',ROUND(REVENUE_2022/1000000000,2),' B') REVENUE_2022,
	CONCAT('$',ROUND(REVENUE_2023/1000000000,2),' B') REVENUE_2023,
	CONCAT('$',ROUND(REVENUE_2024/1000000000,2),' B') REVENUE_2024,
	CASE 
		WHEN REVENUE_2022>0 THEN ROUND(((REVENUE_2024 - REVENUE_2022)/REVENUE_2022)*100,2)
		ELSE 0
	END AS GROWTH_RATE_2022_2024,
	CASE
		WHEN REVENUE_2023>0 THEN ROUND(((REVENUE_2024 - REVENUE_2023)/REVENUE_2023)*100,2)
		ELSE 0
	END AS GROWTH_RATE_2023_2024
FROM REVENUE_GROWTH;